# Generated by Django 5.0.7 on 2024-08-15 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0026_customuser_is_confirmed'),
        ('payment', '0013_payment_hire_request_payment_recruitment_request_and_more'),
        ('service_type', '0003_servicetype_is_active'),
        ('temporary_discount', '0011_remove_custompackage_worked_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('contract_terms', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.customuser')),
                ('package_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage')),
                ('payment_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('request_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_type.servicetype')),
            ],
        ),
    ]
