# Generated by Django 5.0.7 on 2024-08-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_contract_deleted_at'),
        ('payment', '0014_payment_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment', unique=True),
        ),
    ]
