# Generated by Django 5.0.7 on 2024-08-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_contract_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
