# Generated by Django 5.0.7 on 2024-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_alter_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
