# Generated by Django 5.0.7 on 2024-08-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_hire_request_contract_recruitment_request_and_more'),
        ('login', '0027_blacklistedtoken_deleted_at_otpmessage_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
