# Generated by Django 5.0.7 on 2024-08-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_hire_request_contract_recruitment_request_and_more'),
        ('housekeeper', '0067_alter_housekeeper_name'),
        ('login', '0030_alter_customuser_fullname'),
        ('nationality', '0008_alter_nationallity_nationality'),
        ('service_type', '0004_servicetype_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='interest_id',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='service_id',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housekeeper.employmenttype'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterest',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nationality.nationallity'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='service_type.servicetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='status',
            field=models.CharField(blank=True, choices=[('clicked', 'Clicked'), ('abandoned', 'Abandoned')], max_length=20, null=True),
        ),
    ]
