# Generated by Django 5.0.7 on 2024-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_alter_contract_customer_id_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='service_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='status',
            field=models.CharField(blank=True, choices=[('clicked', 'Clicked'), ('abandoned', 'Abandoned')], max_length=20, null=True),
        ),
    ]
