# Generated by Django 5.0.7 on 2024-08-29 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_userinterest_interest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
