# Generated by Django 5.0.7 on 2024-09-13 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_contract_end_date_alter_contract_request_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_terms',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='package_details',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
