# Generated by Django 5.0.7 on 2024-09-13 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_contract_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
