# Generated by Django 5.0.7 on 2024-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_alter_contract_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
