# Generated by Django 5.0.7 on 2024-09-29 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_contract_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 29, 18, 20, 27, 245950, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
