# Generated by Django 5.0.7 on 2024-09-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_userinterest_created_at'),
        ('housekeeper', '0086_notification'),
        ('temporary_discount', '0012_custompackage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='custom_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='temporary_discount.custompackage'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='housekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housekeeper.housekeeper'),
        ),
    ]
