# Generated by Django 5.0.7 on 2024-09-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_userinterest_custom_package_userinterest_housekeeper'),
        ('service_type', '0004_servicetype_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='service_type.servicetype'),
        ),
    ]
