actionlog:
- name: id
  type: BigAutoField
- name: user
  type: ForeignKey
- name: action_type
  type: CharField
- name: description
  type: TextField
- name: timestamp
  type: DateTimeField
blacklistedtoken:
- name: id
  type: BigAutoField
- name: token
  type: CharField
- name: created_at
  type: DateTimeField
contenttype:
- name: id
  type: AutoField
- name: app_label
  type: CharField
- name: model
  type: CharField
customuser:
- name: id
  type: BigAutoField
- name: password
  type: CharField
- name: last_login
  type: DateTimeField
- name: fullName
  type: CharField
- name: phone_number
  type: CharField
- name: dateOfBirth
  type: DateField
- name: nationalID
  type: CharField
- name: is_staff
  type: BooleanField
- name: is_active
  type: BooleanField
emailaddress:
- name: id
  type: AutoField
- name: user
  type: ForeignKey
- name: email
  type: CharField
- name: verified
  type: BooleanField
- name: primary
  type: BooleanField
emailconfirmation:
- name: id
  type: AutoField
- name: email_address
  type: ForeignKey
- name: created
  type: DateTimeField
- name: sent
  type: DateTimeField
- name: key
  type: CharField
employmenttype:
- name: id
  type: BigAutoField
- name: name
  type: CharField
group:
- name: id
  type: AutoField
- name: name
  type: CharField
- name: permissions
  type: ManyToManyField
hirerequest:
- name: id
  type: BigAutoField
- name: housekeeper
  type: ForeignKey
- name: requester
  type: ForeignKey
- name: requester_contact
  type: CharField
- name: request_date
  type: DateField
- name: duration
  type: IntegerField
- name: pericepernationality_id
  type: ForeignKey
- name: total_price
  type: FloatField
- name: status
  type: ForeignKey
housekeeper:
- name: id
  type: BigAutoField
- name: Name
  type: CharField
- name: Age
  type: IntegerField
- name: gender
  type: CharField
- name: nationality
  type: ForeignKey
- name: religion
  type: ForeignKey
- name: isactive
  type: BooleanField
- name: is_available
  type: BooleanField
- name: worked_before
  type: BooleanField
- name: worked_before_salary
  type: FloatField
- name: employment_type
  type: ForeignKey
logentry:
- name: id
  type: AutoField
- name: action_time
  type: DateTimeField
- name: user
  type: ForeignKey
- name: content_type
  type: ForeignKey
- name: object_id
  type: TextField
- name: object_repr
  type: CharField
- name: action_flag
  type: PositiveSmallIntegerField
- name: change_message
  type: TextField
nationallity:
- name: id
  type: BigAutoField
- name: Nationality
  type: CharField
payment:
- name: id
  type: BigAutoField
- name: action
  type: CharField
- name: result
  type: CharField
- name: status
  type: CharField
- name: order_id
  type: CharField
- name: trans_id
  type: CharField
- name: trans_date
  type: DateTimeField
- name: descriptor
  type: CharField
- name: recurring_token
  type: CharField
- name: schedule_id
  type: CharField
- name: card_token
  type: CharField
- name: amount
  type: DecimalField
- name: currency
  type: CharField
- name: decline_reason
  type: TextField
- name: redirect_url
  type: CharField
- name: redirect_params
  type: JSONField
- name: redirect_method
  type: CharField
- name: card
  type: CharField
- name: card_expiration_date
  type: CharField
- name: hash
  type: CharField
- name: source
  type: CharField
pericepernationality:
- name: id
  type: BigAutoField
- name: nationality
  type: ForeignKey
- name: service_type
  type: ForeignKey
- name: employment_type
  type: ForeignKey
- name: worked_before
  type: BooleanField
- name: price
  type: FloatField
permission:
- name: id
  type: AutoField
- name: name
  type: CharField
- name: content_type
  type: ForeignKey
- name: codename
  type: CharField
recruitmentrequest:
- name: id
  type: BigAutoField
- name: housekeeper
  type: ForeignKey
- name: requester
  type: ForeignKey
- name: request_contact
  type: CharField
- name: visa_status
  type: BooleanField
- name: requested_date
  type: DateField
- name: status
  type: ForeignKey
religion:
- name: id
  type: BigAutoField
- name: name
  type: CharField
role:
- name: id
  type: BigAutoField
- name: name
  type: CharField
servicetype:
- name: id
  type: BigAutoField
- name: name
  type: CharField
session:
- name: session_key
  type: CharField
- name: session_data
  type: TextField
- name: expire_date
  type: DateTimeField
site:
- name: id
  type: AutoField
- name: domain
  type: CharField
- name: name
  type: CharField
socialaccount:
- name: id
  type: AutoField
- name: user
  type: ForeignKey
- name: provider
  type: CharField
- name: uid
  type: CharField
- name: last_login
  type: DateTimeField
- name: date_joined
  type: DateTimeField
- name: extra_data
  type: JSONField
socialapp:
- name: id
  type: AutoField
- name: provider
  type: CharField
- name: provider_id
  type: CharField
- name: name
  type: CharField
- name: client_id
  type: CharField
- name: secret
  type: CharField
- name: key
  type: CharField
- name: settings
  type: JSONField
- name: sites
  type: ManyToManyField
socialtoken:
- name: id
  type: AutoField
- name: app
  type: ForeignKey
- name: account
  type: ForeignKey
- name: token
  type: TextField
- name: token_secret
  type: TextField
- name: expires_at
  type: DateTimeField
status:
- name: id
  type: BigAutoField
- name: Status
  type: CharField
token:
- name: key
  type: CharField
- name: user
  type: OneToOneField
- name: created
  type: DateTimeField
tokenproxy:
- name: key
  type: CharField
- name: user
  type: OneToOneField
- name: created
  type: DateTimeField
transferrequest:
- name: id
  type: BigAutoField
- name: housekeeper
  type: ForeignKey
- name: requester
  type: ForeignKey
- name: requested_date
  type: DateField
- name: status
  type: ForeignKey
user:
- name: id
  type: AutoField
- name: password
  type: CharField
- name: last_login
  type: DateTimeField
- name: is_superuser
  type: BooleanField
- name: username
  type: CharField
- name: first_name
  type: CharField
- name: last_name
  type: CharField
- name: email
  type: CharField
- name: is_staff
  type: BooleanField
- name: is_active
  type: BooleanField
- name: date_joined
  type: DateTimeField
- name: groups
  type: ManyToManyField
- name: user_permissions
  type: ManyToManyField
