# Generated by Django 5.0.7 on 2024-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0005_nationallity_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationallity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nationality_images/'),
        ),
    ]
