# Generated by Django 5.0.7 on 2024-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0007_alter_nationallity_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationallity',
            name='Nationality',
            field=models.CharField(max_length=150),
        ),
    ]
