# Generated by Django 5.0.7 on 2024-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SALE', 'Sale'), ('3DS', '3D Secure'), ('REDIRECT', 'Redirect'), ('REFUND', 'Refund'), ('RECURRING', 'Recurring')], max_length=50)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('DECLINED', 'Declined'), ('REDIRECT', 'Redirect'), ('ACCEPTED', 'Accepted'), ('ERROR', 'Error')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('3DS', '3D Secure'), ('REDIRECT', 'Redirect'), ('SETTLED', 'Settled'), ('REFUND', 'Refund'), ('DECLINED', 'Declined')], max_length=50, null=True)),
                ('order_id', models.CharField(max_length=100)),
                ('trans_id', models.CharField(max_length=100)),
                ('trans_date', models.DateTimeField()),
                ('descriptor', models.CharField(blank=True, max_length=255, null=True)),
                ('recurring_token', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_token', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('redirect_params', models.JSONField(blank=True, null=True)),
                ('redirect_method', models.CharField(blank=True, max_length=10, null=True)),
                ('card', models.CharField(blank=True, max_length=255, null=True)),
                ('card_expiration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
