# Generated by Django 5.0.7 on 2024-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_hash_remove_payment_recurring_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='apple_pay_description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='apple_pay_hash',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='apple_pay_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='apple_pay_order_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manafith_description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manafith_hash',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manafith_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manafith_order_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manafith_source',
        ),
        migrations.AddField(
            model_name='payment',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recurring_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='schedule_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='action',
            field=models.CharField(choices=[('SALE', 'Sale'), ('3DS', '3D Secure'), ('REDIRECT', 'Redirect'), ('REFUND', 'Refund'), ('RECURRING', 'Recurring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('DECLINED', 'Declined'), ('REDIRECT', 'Redirect'), ('ACCEPTED', 'Accepted'), ('ERROR', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('3DS', '3D Secure'), ('REDIRECT', 'Redirect'), ('SETTLED', 'Settled'), ('REFUND', 'Refund'), ('DECLINED', 'Declined'), ('PREPARE', 'Prepare'), ('PENDING', 'Pending')], max_length=50, null=True),
        ),
    ]
