# Generated by Django 5.0.7 on 2024-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_result_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trans_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
