# Generated by Django 5.0.7 on 2024-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('3DS', '3D Secure'), ('REDIRECT', 'Redirect'), ('SETTLED', 'Settled'), ('REFUND', 'Refund'), ('DECLINED', 'Declined'), ('PREPARE', 'Prepare'), ('PENDING', 'Pending'), ('success', 'Success'), ('fail', 'Fail')], max_length=50, null=True),
        ),
    ]
