# Generated by Django 5.0.7 on 2024-08-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0042_rename_requested_date_recruitmentrequest_request_date_and_more'),
        ('payment', '0012_alter_payment_currency_alter_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.hirerequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recruitment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.recruitmentrequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.transferrequest'),
        ),
    ]
