# Generated by Django 5.0.7 on 2024-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
