# Generated by Django 5.0.7 on 2024-07-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_roleuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
