# Generated by Django 5.0.7 on 2024-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
