# Generated by Django 5.0.7 on 2024-07-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
