# Generated by Django 5.0.7 on 2024-07-28 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_customuser_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationalID',
            field=models.CharField(default='1234567890o', max_length=100),
        ),
    ]
