# Generated by Django 5.0.7 on 2024-08-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_revokedtoken_user_alter_revokedtoken_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevokedToken',
            new_name='BlacklistedToken',
        ),
    ]
