# Generated by Django 5.0.7 on 2024-08-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_revokedtoken_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
