# Generated by Django 5.0.7 on 2024-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_customuser_email_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
