# Generated by Django 5.0.7 on 2024-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_blacklistedtoken_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
