# Generated by Django 5.0.7 on 2024-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_blacklistedtoken_is_active_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
