# Generated by Django 5.0.7 on 2024-08-25 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_blacklistedtoken_deleted_at_otpmessage_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
