# Generated by Django 5.0.7 on 2024-08-28 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
