# Generated by Django 5.0.7 on 2024-08-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullName',
            field=models.CharField(max_length=150),
        ),
    ]
