# Generated by Django 5.0.7 on 2024-08-31 07:31

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_alter_customuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nationalID',
            field=models.CharField(max_length=100, validators=[login.models.validate_saudi_national_id]),
        ),
    ]
