# Generated by Django 5.0.7 on 2024-08-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_alter_customuser_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nationalID',
        ),
    ]
