# Generated by Django 5.0.7 on 2024-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_remove_customuser_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmessage',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='otpmessage',
            name='otp',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='otpmessage',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpmessage',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpmessage',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
