# Generated by Django 5.0.7 on 2024-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_remove_otpmessage_deleted_at_otpmessage_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
