# Generated by Django 5.0.7 on 2024-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_otpmessage_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmessage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
