# Generated by Django 5.0.7 on 2024-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_otpmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
