# Generated by Django 5.0.7 on 2024-08-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_alter_otpmessage_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmessage',
            name='deleted_at',
        ),
    ]
