# Generated by Django 5.0.7 on 2024-08-31 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_otpmessage_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
