# Generated by Django 5.0.7 on 2024-08-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_alter_otpmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=10)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='otpmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otpmessage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='otpmessage',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='otpmessage',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='otpmessage',
            name='request_body',
        ),
        migrations.RemoveField(
            model_name='otpmessage',
            name='response_body',
        ),
    ]
