# Generated by Django 5.0.7 on 2024-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_otplog_remove_otpmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otplog',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
