# Generated by Django 5.0.7 on 2024-09-22 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_otplog_response_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='contact number must start with 05.', regex='^05'), django.core.validators.RegexValidator(message='contact number must have 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
