# Generated by Django 5.0.7 on 2024-09-28 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='contact number must start with 966.', regex='^966'), django.core.validators.RegexValidator(message='contact number must have 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
