# Generated by Django 5.0.7 on 2024-08-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0012_hirerequest_duration_and_more'),
        ('perice_per_nationality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pericepernationality',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.employmenttype'),
        ),
    ]
