# Generated by Django 5.0.7 on 2024-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perice_per_nationality', '0002_pericepernationality_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pericepernationality',
            name='worked_before',
            field=models.BooleanField(default=True),
        ),
    ]
