# Generated by Django 5.0.7 on 2024-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perice_per_nationality', '0003_pericepernationality_worked_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pericepernationality',
            old_name='price',
            new_name='fees',
        ),
        migrations.AddField(
            model_name='pericepernationality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pericepernationality',
            name='new_housekeeper_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pericepernationality',
            name='worked_before_salary',
            field=models.FloatField(null=True),
        ),
    ]
