# Generated by Django 5.0.7 on 2024-08-12 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perice_per_nationality', '0004_rename_price_pericepernationality_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericepernationality',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
