# Generated by Django 5.0.7 on 2024-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perice_per_nationality', '0005_alter_pericepernationality_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pericepernationality',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
