# Generated by Django 5.0.7 on 2024-08-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perice_per_nationality', '0006_pericepernationality_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pericepernationality',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
