# Generated by Django 5.0.7 on 2024-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('Cleaing', 'Cleaning'), ('Cooking', 'Cooking'), ('Cleaning & Cooking', 'Cleaning & Cooking'), ('Nanny', 'Nanny')], max_length=20)),
            ],
        ),
    ]
