# Generated by Django 5.0.7 on 2024-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeeper',
            name='pricePerMonth',
        ),
        migrations.AddField(
            model_name='housekeeper',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housekeeper',
            name='isvailability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='visa_status',
            field=models.BooleanField(default=False),
        ),
    ]
