# Generated by Django 5.0.7 on 2024-07-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0002_remove_housekeeper_pricepermonth_and_more'),
        ('nationality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationality.nationallity'),
        ),
    ]
