# Generated by Django 5.0.7 on 2024-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0006_alter_hirerequest_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housekeeper',
            old_name='isvailability',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='housekeeper',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
