# Generated by Django 5.0.7 on 2024-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0007_rename_isvailability_housekeeper_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
