# Generated by Django 5.0.7 on 2024-07-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0008_alter_housekeeper_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
    ]
