# Generated by Django 5.0.7 on 2024-07-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0009_alter_hirerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeper',
            name='worked_before',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
    ]
