# Generated by Django 5.0.7 on 2024-08-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0013_rename_pericepernationalit_id_hirerequest_pericepernationality_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeeper',
            name='montly_salary',
        ),
        migrations.RemoveField(
            model_name='housekeeper',
            name='pricePerMonth',
        ),
    ]
