# Generated by Django 5.0.7 on 2024-08-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0018_employmenttype_is_active_hirerequest_requester_city_and_more'),
        ('temporary_discount', '0002_alter_promotioncode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='temporary_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.tempoararydiscount'),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='temporary_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.tempoararydiscount'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requester_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requester_firstName',
            field=models.CharField(default='DefaultFirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requester_lastName',
            field=models.CharField(default='DefaultLastName', max_length=100),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='temporary_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.tempoararydiscount'),
        ),
    ]
