# Generated by Django 5.0.7 on 2024-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0019_hirerequest_temporary_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
