# Generated by Django 5.0.7 on 2024-08-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0020_hirerequest_is_discount_and_more'),
        ('perice_per_nationality', '0005_alter_pericepernationality_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='is_discount',
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='pericepernationality_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perice_per_nationality.pericepernationality'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='pericepernationality_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perice_per_nationality.pericepernationality'),
        ),
    ]
