# Generated by Django 5.0.7 on 2024-08-12 11:51

import django.db.models.deletion
import housekeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0023_recruitmentrequest_service_type_and_more'),
        ('service_type', '0003_servicetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='service_type',
            field=models.ForeignKey(default=housekeeper.models.HireRequest.get_default_service_type, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_type.servicetype'),
        ),
    ]
