# Generated by Django 5.0.7 on 2024-08-12 11:53

import django.db.models.deletion
import housekeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0024_alter_hirerequest_service_type'),
        ('service_type', '0003_servicetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='service_type',
            field=models.ForeignKey(default=housekeeper.models.RecruitmentRequest.get_default_service_type, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_type.servicetype'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='service_type',
            field=models.ForeignKey(default=housekeeper.models.TransferRequest.get_default_service_type, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_type.servicetype'),
        ),
    ]
