# Generated by Django 5.0.7 on 2024-08-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0028_housekeeperrequesttype'),
        ('service_type', '0003_servicetype_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeeper',
            name='request_types',
        ),
        migrations.AlterUniqueTogether(
            name='housekeeperrequesttype',
            unique_together={('housekeeper', 'request_type')},
        ),
    ]
