# Generated by Django 5.0.7 on 2024-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0030_alter_housekeeperrequesttype_id'),
        ('service_type', '0003_servicetype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeper',
            name='request_types',
            field=models.ManyToManyField(related_name='housekeeper', through='housekeeper.HousekeeperRequestType', to='service_type.servicetype'),
        ),
    ]
