# Generated by Django 5.0.7 on 2024-08-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0031_housekeeper_request_types'),
        ('temporary_discount', '0011_remove_custompackage_worked_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='pericepernationality_id',
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='custom_package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage'),
        ),
    ]
