# Generated by Django 5.0.7 on 2024-08-15 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0032_remove_hirerequest_pericepernationality_id_and_more'),
        ('temporary_discount', '0011_remove_custompackage_worked_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirerequest',
            old_name='service_type',
            new_name='request_type',
        ),
        migrations.RenameField(
            model_name='recruitmentrequest',
            old_name='service_type',
            new_name='request_type',
        ),
        migrations.RenameField(
            model_name='transferrequest',
            old_name='service_type',
            new_name='request_type',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='temporary_discount',
        ),
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='temporary_discount',
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='custom_package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='custom_package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage'),
        ),
    ]
