# Generated by Django 5.0.7 on 2024-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0034_hirerequest_temporary_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
