# Generated by Django 5.0.7 on 2024-08-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0035_hirerequest_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='order_id',
        ),
    ]
