# Generated by Django 5.0.7 on 2024-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0037_hirerequest_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentrequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
