# Generated by Django 5.0.7 on 2024-08-15 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0038_recruitmentrequest_order_id_transferrequest_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitmentrequest',
            old_name='request_contact',
            new_name='requester_contact',
        ),
        migrations.RenameField(
            model_name='transferrequest',
            old_name='request_contact',
            new_name='requester_contact',
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 9, 3, 55, 694098, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 9, 3, 55, 694098, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 9, 3, 55, 694098, tzinfo=datetime.timezone.utc)),
        ),
    ]
