# Generated by Django 5.0.7 on 2024-08-15 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0039_rename_request_contact_recruitmentrequest_requester_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 9, 6, 9, 166868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 9, 6, 9, 166868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 9, 6, 9, 182489, tzinfo=datetime.timezone.utc)),
        ),
    ]
