# Generated by Django 5.0.7 on 2024-08-15 09:09

import housekeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0040_alter_hirerequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='request_date',
            field=models.DateField(default=housekeeper.models.HireRequest.get_current_date),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='requested_date',
            field=models.DateField(default=housekeeper.models.RecruitmentRequest.get_current_date),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requested_date',
            field=models.DateField(default=housekeeper.models.TransferRequest.get_current_date),
        ),
    ]
