# Generated by Django 5.0.7 on 2024-08-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0042_rename_requested_date_recruitmentrequest_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='pericepernationality_id',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='pericepernationality_id',
        ),
    ]
