# Generated by Django 5.0.7 on 2024-08-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0044_actionlog_deleted_at_employmenttype_deleted_at_and_more'),
        ('login', '0027_blacklistedtoken_deleted_at_otpmessage_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customuser'),
        ),
    ]
