# Generated by Django 5.0.7 on 2024-08-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0045_actionlog_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
    ]
