# Generated by Django 5.0.7 on 2024-08-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0046_alter_hirerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentrequest',
            name='requester_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='requester_firstName',
            field=models.CharField(default='DefaultFirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='requester_lastName',
            field=models.CharField(default='DefaultLastName', max_length=100),
        ),
    ]
