# Generated by Django 5.0.7 on 2024-08-20 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0048_alter_recruitmentrequest_requester_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
    ]
