# Generated by Django 5.0.7 on 2024-08-20 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0050_alter_recruitmentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='status',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
    ]
