# Generated by Django 5.0.7 on 2024-08-20 06:17

import django.db.models.deletion
import housekeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0051_alter_hirerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.ForeignKey(blank=True, default=housekeeper.models.HireRequest.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='status',
            field=models.ForeignKey(blank=True, default=housekeeper.models.RecruitmentRequest.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.ForeignKey(blank=True, default=housekeeper.models.TransferRequest.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.status'),
        ),
    ]
