# Generated by Django 5.0.7 on 2024-08-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0052_alter_hirerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='requester_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='requester_firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='requester_lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_lastName',
            field=models.CharField(max_length=100),
        ),
    ]
