# Generated by Django 5.0.7 on 2024-08-25 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0053_alter_hirerequest_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='requester_contact',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="contact numbber must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='housekeeper',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='requester_contact',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="contact numbber must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_contact',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="contact numbber must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
