# Generated by Django 5.0.7 on 2024-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0055_alter_hirerequest_requester_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housekeeper',
            name='languages_spoken',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housekeeper',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
