# Generated by Django 5.0.7 on 2024-08-26 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0057_alter_housekeeper_nationality'),
        ('temporary_discount', '0012_custompackage_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='custom_package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='temporary_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.tempoararydiscount'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='custom_package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage'),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='temporary_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.tempoararydiscount'),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='custom_package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.custompackage'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='temporary_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporary_discount.tempoararydiscount'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='tax_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.taxes'),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='tax_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.taxes'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='tax_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.taxes'),
        ),
    ]
