# Generated by Django 5.0.7 on 2024-08-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0058_taxes_hirerequest_tax_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='tax_amount',
        ),
    ]
