# Generated by Django 5.0.7 on 2024-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0059_remove_transferrequest_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
