# Generated by Django 5.0.7 on 2024-08-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0060_transferrequest_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='tax_amount',
        ),
    ]
