# Generated by Django 5.0.7 on 2024-08-26 08:43

import django.db.models.deletion
import housekeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0062_recruitmentrequest_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='tax_id',
            field=models.ForeignKey(blank=True, default=housekeeper.models.HireRequest.get_default_taxes, null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.taxes'),
        ),
    ]
