# Generated by Django 5.0.7 on 2024-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0066_hirerequest_price_recruitmentrequest_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
