# Generated by Django 5.0.7 on 2024-08-31 12:28

import django.utils.timezone
import housekeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0067_alter_housekeeper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='nationalID',
            field=models.CharField(default=0, max_length=100, validators=[housekeeper.models.validate_saudi_national_id]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='requester_fatherName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housekeeper',
            name='Identification_number',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='nationalID',
            field=models.CharField(default=0, max_length=100, validators=[housekeeper.models.validate_saudi_national_id]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='requester_fatherName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='nationalID',
            field=models.CharField(default=0, max_length=100, validators=[housekeeper.models.validate_saudi_national_id]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requester_fatherName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
