# Generated by Django 5.0.7 on 2024-09-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0067_alter_housekeeper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='requester_fatherName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housekeeper',
            name='Identification_number',
            field=models.CharField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='requester_fatherName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requester_fatherName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
