# Generated by Django 5.0.7 on 2024-08-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0069_alter_housekeeper_identification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='dateOfBirth',
        ),
    ]
