# Generated by Django 5.0.7 on 2024-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0070_remove_hirerequest_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='nationalID',
        ),
    ]
