# Generated by Django 5.0.7 on 2024-08-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0071_remove_hirerequest_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='contract_file',
        ),
    ]
