# Generated by Django 5.0.7 on 2024-08-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0073_hirerequest_contract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='nationalID',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='nationalID',
        ),
        migrations.AddField(
            model_name='recruitmentrequest',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
