# Generated by Django 5.0.7 on 2024-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0075_remove_recruitmentrequest_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentrequest',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
