# Generated by Django 5.0.7 on 2024-08-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0076_recruitmentrequest_contract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='contract_file',
        ),
    ]
