# Generated by Django 5.0.7 on 2024-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0077_remove_transferrequest_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='contract_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
