# Generated by Django 5.0.7 on 2024-08-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0078_transferrequest_contract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentrequest',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='contract_file',
        ),
    ]
