# Generated by Django 5.0.7 on 2024-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0079_remove_recruitmentrequest_contract_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirerequest',
            name='contract_file',
        ),
        migrations.AlterField(
            model_name='housekeeper',
            name='Identification_number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
