# Generated by Django 5.0.7 on 2024-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0080_remove_hirerequest_contract_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeper',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
