# Generated by Django 5.0.7 on 2024-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0081_housekeeper_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
