# Generated by Django 5.0.7 on 2024-09-22 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0082_alter_housekeeper_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='requester_contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='contact number must start with 05.', regex='^05'), django.core.validators.RegexValidator(message='contact number must have 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='requester_contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='contact number must start with 05.', regex='^05'), django.core.validators.RegexValidator(message='contact number must have 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='contact number must start with 05.', regex='^05'), django.core.validators.RegexValidator(message='contact number must have 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
