# Generated by Django 5.0.7 on 2024-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0083_alter_hirerequest_requester_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
