# Generated by Django 5.0.7 on 2024-09-28 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0084_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='requester_contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='contact number must start with 966.', regex='^966'), django.core.validators.RegexValidator(message='contact number must have 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='requester_contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='contact number must start with 966.', regex='^966'), django.core.validators.RegexValidator(message='contact number must have 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requester_contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='contact number must start with 966.', regex='^966'), django.core.validators.RegexValidator(message='contact number must have 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
