# Generated by Django 5.0.7 on 2024-08-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_per_user', '0002_alter_roleperuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleperuser',
            old_name='name',
            new_name='role',
        ),
    ]
