# Generated by Django 5.0.7 on 2024-08-14 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_customuser_is_confirmed'),
        ('role', '0002_alter_role_id'),
        ('role_per_user', '0003_rename_name_roleperuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePerClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clients', models.ManyToManyField(related_name='roles', to='login.customuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role')),
            ],
        ),
    ]
