# Generated by Django 5.0.7 on 2024-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_per_user', '0004_roleperclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleperclient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleperuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
