# Generated by Django 5.0.7 on 2024-10-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_per_user', '0005_roleperclient_deleted_at_roleperuser_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleperuser',
            name='users',
        ),
    ]
