# Generated by Django 5.0.7 on 2024-08-10 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perice_per_nationality', '0003_pericepernationality_worked_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price_per_nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perice_per_nationality.pericepernationality')),
            ],
        ),
        migrations.CreateModel(
            name='TempoararyDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price_per_nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perice_per_nationality.pericepernationality')),
            ],
        ),
    ]
