# Generated by Django 5.0.7 on 2024-08-11 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0004_nationallity_is_active'),
        ('service_type', '0003_servicetype_is_active'),
        ('temporary_discount', '0002_alter_promotioncode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_indefinitely', models.BooleanField(default=False)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_packages', to='nationality.nationallity')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_packages', to='service_type.servicetype')),
            ],
        ),
    ]
