# Generated by Django 5.0.7 on 2024-08-12 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_discount', '0004_custompackage_is_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
