# Generated by Django 5.0.7 on 2024-08-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0004_nationallity_is_active'),
        ('temporary_discount', '0005_alter_custompackage_id_alter_promotioncode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageNationallity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationallities', to='temporary_discount.custompackage')),
                ('nationallity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationality.nationallity')),
            ],
            options={
                'unique_together': {('custom_package', 'nationallity')},
            },
        ),
    ]
