# Generated by Django 5.0.7 on 2024-08-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_discount', '0006_custompackagenationallity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompackage',
            name='nationality',
        ),
    ]
