# Generated by Django 5.0.7 on 2024-08-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0004_nationallity_is_active'),
        ('temporary_discount', '0007_remove_custompackage_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='nationallities',
            field=models.ManyToManyField(through='temporary_discount.CustomPackageNationallity', to='nationality.nationallity'),
        ),
        migrations.AlterField(
            model_name='custompackagenationallity',
            name='custom_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_package_nationallities', to='temporary_discount.custompackage'),
        ),
        migrations.AlterField(
            model_name='custompackagenationallity',
            name='nationallity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_package_nationallities', to='nationality.nationallity'),
        ),
    ]
