# Generated by Django 5.0.7 on 2024-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0004_nationallity_is_active'),
        ('temporary_discount', '0008_custompackage_nationallities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='nationallities',
            field=models.ManyToManyField(related_name='custom_packages', through='temporary_discount.CustomPackageNationallity', to='nationality.nationallity'),
        ),
    ]
