# Generated by Django 5.0.7 on 2024-08-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeper', '0031_housekeeper_request_types'),
        ('temporary_discount', '0009_alter_custompackage_nationallities'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housekeeper.employmenttype'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='new_housekeeper_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='worked_before',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='worked_before_salary',
            field=models.FloatField(null=True),
        ),
    ]
