# Generated by Django 5.0.7 on 2024-08-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_discount', '0010_custompackage_employment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompackage',
            name='worked_before',
        ),
        migrations.RemoveField(
            model_name='tempoararydiscount',
            name='price_per_nationality',
        ),
    ]
