# Generated by Django 5.0.7 on 2024-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_discount', '0011_remove_custompackage_worked_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custompackagenationallity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
