name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]  # Updated to use Python 3.12

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip freeze > requirements.txt
    - name: Install django-cors-headers
      run: |
        pip install django-cors-headers

    - name: Run Tests
      run: |
        python manage.py test

        - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@payload.ifuture.sa << 'EOF'
          cd /root/Housekeeper-APP
          git pull origin main
          
          # Optional: Restart services or perform other deployment tasks
          # e.g., restart server, migrate database, etc.
          # systemctl restart your-service
        EOF
